name: Auto Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version bump type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Install dependencies
        working-directory: ./react-live2d-lipsync
        run: npm ci

      - name: Run validation
        working-directory: ./react-live2d-lipsync
        run: npm run validate

      - name: Bump version
        working-directory: ./react-live2d-lipsync
        run: |
          npm version ${{ inputs.version_type }} -m "chore: bump version to %s"
          echo "NEW_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Build package
        working-directory: ./react-live2d-lipsync
        run: npm run build

      - name: Commit dist files
        run: |
          cd react-live2d-lipsync
          git add dist/
          git diff --staged --quiet || git commit -m "build: update dist files for v${{ env.NEW_VERSION }}"

      - name: Push changes
        run: |
          git push origin main
          git push origin v${{ env.NEW_VERSION }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.NEW_VERSION }}
          name: Release v${{ env.NEW_VERSION }}
          body: |
            ## Installation

            ```bash
            npm install Yuta-Hachino/react-live2d-lipsync#v${{ env.NEW_VERSION }}
            ```

            ## What's Changed

            - Version bumped to ${{ env.NEW_VERSION }}
            - Updated build files

            **Full Changelog**: https://github.com/${{ github.repository }}/compare/v${{ env.PREVIOUS_VERSION }}...v${{ env.NEW_VERSION }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
